import streamlit as st
import json
import os

st.set_page_config(
    page_title="The A.S.E.R.K.A.R. Framework",
    layout="wide",
    page_icon="🔺"
)

# Centered Logo and Framework Heading
header_col1, header_col2, header_col3 = st.columns([1.5, 1, 1.5])

with header_col2:
    if os.path.exists("logo1.png"):
        st.image("logo1.png", use_container_width=True)
    else:
        st.warning("logo1.png not found. Please upload it to the repository.")

st.markdown(
    """
    <div style="text-align: center; margin-top: 0px; margin-bottom: 25px;">
        <h1 style="margin-bottom: 4px; font-weight: 800; letter-spacing: 0.5px;">The A.S.E.R.K.A.R. Framework</h1>
        <p style="color: #94A3B8; font-size: 15px; margin-top: 0px; font-weight: 400;">
            ( Anticipatory Supply-chain Engine for Risk, Knowledge, and Automated Resilience )
        </p>
    </div>
    """,
    unsafe_allow_html=True
)

st.title("🌐 Weekly Disruption Synthesis")
st.markdown("Macro-level intelligence briefing tracking critical disruption vectors across global manufacturing.")
st.divider()

json_path = "data/intelligence.json"

if os.path.exists(json_path):
    try:
        with open(json_path, "r") as f:
            data = json.load(f)
            
        if data and isinstance(data, list) and "master_report" in data[0]:
            report = data[0]
            st.caption(f"**Latest Synthesis Generated:** {report.get('date_collected')}")
            
            # Displaying the single master report generated by Gemini
            with st.container(border=True):
                st.markdown(report.get("master_report", "Report empty."))
        else:
            st.info("Awaiting next automated collection cycle to generate the master report.")
            
    except json.JSONDecodeError:
        st.error("Intelligence database is corrupted or empty.")
else:
    st.warning("Intelligence database not found. Please run the collector script.")
